title: "Crackmy Writeups"
description: "Reverse engineering challenges & solutions"
theme: minima

# Apply default layout only to individual challenge index.md files
defaults:
  - scope:
      path: "_challenges"
      type: challenges
    values:
      layout: challenge_page  # Custom layout for challenge pages


# Enable the 'challenges' collection and set output to true
collections:
  challenges:
    output: true  # Ensure pages are generated for individual challenges
    permalink: /_challenges/:path/  # New permalink structure

# Do not include _challenges here; Jekyll will handle collections automatically
exclude:
  - _challenges/*.md  # Exclude challenge markdown files from other processing
